### ISSUE TITLE
Need help with postproccesing on rockchip YOLOv8)

### ISSUE THREAD

**Issue by ViktorPavlovA** [oleg-milantiev/ros2-vedrus#1]
**Hello.** 

I find your article : https://oleg.milantiev.com/2024/02/25/yolov8-npu-rk3588-orange-pi-3b/

So i stopped on post processing i also get some tensors. How you get bbox? Or maybe you have source code of post processing?  

**Thank you!**

**Comment by oleg-milantiev** [comment]
Hi!

Here is postprocessor: https://github.com/oleg-milantiev/ros2-vedrus/blob/main/yolov8_rknn/yolov8_rknn/solver.py

(look for def post_process)
